const ADD_PLAYER = `ADD_PLAYER`;
const REMOVE_PLAYER = `REMOVE_PLAYER`;
const ADD_PLAYER_DATA = `ADD_PLAYER_DATA`;

const ADD_PLACE= `ADD_PLACE`;
const RESET = `RESET`;

export {ADD_PLAYER, REMOVE_PLAYER, ADD_PLAYER_DATA, RESET, ADD_PLACE}